# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/Authenticate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(290, 235)
        Dialog.setMinimumSize(QtCore.QSize(290, 235))
        Dialog.setMaximumSize(QtCore.QSize(290, 235))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("interfaces/../assets/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.btnLayout = QtWidgets.QVBoxLayout(Dialog)
        self.btnLayout.setObjectName("btnLayout")
        self.errorLayout = QtWidgets.QVBoxLayout()
        self.errorLayout.setObjectName("errorLayout")
        self.btnLayout.addLayout(self.errorLayout)
        self.Label = QtWidgets.QLabel(Dialog)
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.btnLayout.addWidget(self.Label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(Dialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.passwdLabel = QtWidgets.QLabel(Dialog)
        self.passwdLabel.setObjectName("passwdLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwdLabel)
        self.usernameInput = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.usernameInput.setFont(font)
        self.usernameInput.setText("")
        self.usernameInput.setObjectName("usernameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameInput)
        self.passwdInput = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.passwdInput.setFont(font)
        self.passwdInput.setText("")
        self.passwdInput.setObjectName("passwdInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwdInput)
        self.btnLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reg = QtWidgets.QPushButton(Dialog)
        self.reg.setObjectName("reg")
        self.horizontalLayout.addWidget(self.reg)
        self.login = QtWidgets.QPushButton(Dialog)
        self.login.setObjectName("login")
        self.horizontalLayout.addWidget(self.login)
        self.btnLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Authenticate"))
        self.Label.setText(_translate("Dialog", "Enter User Credential: "))
        self.usernameLabel.setText(_translate("Dialog", "Username:"))
        self.passwdLabel.setText(_translate("Dialog", "Password:"))
        self.reg.setText(_translate("Dialog", "Register"))
        self.login.setText(_translate("Dialog", "Login"))
